### ISSUE TITLE
Todo's

### ISSUE THREAD

**Issue by mohammed-ibrahim** [mohammed-ibrahim/jump#1]
- [ ] sql support
- [ ] Make jump scripts like programming language
- [ ] Remove logback.xml
- [x] Clean logger
- [x] releases in github
- [x] implement random between
- [x] section -> from_section
- [x] Get the work done by fetchers()
- [x] Use iterative wrapped class
- [x] include function between(1, 100)
- [x] include function serial(a, b, c, d, e, ...)
- [x] include function any_of( x ,y, z, a ....)
- [x] multi iterative
- [ ] run internal sql script
- [ ] run external sql script
- [x] custom fake factory
- [x] linear fetcher for the indexes
- [ ] log debug to file and only info to console
- [ ] unique constraints - cross product or... some product
- [ ] text builder
- [x] Config validator
- [ ] raw sql execute
- [x] transactional
- [ ] Create Wiki page for config
- [ ] File logging
- [ ] Fix logger to consume from logback.xml
- [ ] Add shutdown hook
- [ ] Memory management options settings
